apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- discourse.yaml
- ingress.yaml
- secret.yaml
- postgresql.yaml
- namespace.yaml
- pvc.yaml
- redis.yaml
- autoscaler.yaml
commonAnnotations:
  kubernetes.ops.cluster: test
  kubernetes.ops.email: wangweifeng21@huawei.com
  kubernetes.ops.os.base: debian
  kubernetes.ops.owner: wangweifeng
  kubernetes.ops.region: hk
namespace: discourse
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/discourse
  newTag: v1.5.0
