apiVersion: v1
kind: ConfigMap
metadata:
  name: signatrust-client-configmap
  namespace: openeuler-signatrust
data:
  client.toml: |
    working_dir = "/Users/tommylike/Work/codes/rust-projects/signatrust/.data/tempdir"
    worker_threads = 8
    buffer_size = 20480
    # consider the memory consumption if number bumped since all binaries will be stored in memory
    max_concurrency = 100
    [server]
    domain_name = "signatrust.test.osinfra.cn"
    tls_cert = "/Users/tommylike/Work/codes/rust-projects/signatrust/.data/certs/client/server.crt"
    tls_key = "/Users/tommylike/Work/codes/rust-projects/signatrust/.data/certs/client/server.key"
    type = "dns"
    server_name = "data-server-headless.openeuler-signatrust.svc.cluster.local"
    server_port = "8088"