---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/whitelist-source-range: 49.0.228.19
  name: oneid-server-ingress
  namespace: om-webserver
spec:
  tls:
    - hosts:
      - oneid.myopeninfra.com
      secretName: oneid-server-tls
  rules:
    - host: oneid.myopeninfra.com
      http:
        paths:
        - backend:
            serviceName: oneid-server-service
            servicePort: 80
          path: /