resources:
  - git
  - github
  - gitee
  - website
  - openlab
  - git_commit
  - git_commit_all
  - github_pr_issue
  - blue_zone_user
  - white_git
  - namespace.yaml
  - gitee_github_combine
  - git-commit-log
  - git-commit-log-enterprise
  - white-commit-log
  - upstream-commit-log
  - tag-removed-gitee
  - gitlab-pr-issue-commit
  - github_spark_pr_issue
  - github_pytorch_pr_issue
  - github_tensorflow_pr_issue
  - gitee_enterprise
namespace: kunpeng-om
