resources:
- namespace.yaml
- ingress.yaml
- service.yaml
- deployment.yaml
- secret.yaml
namespace: community-talent-certification-it-system
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/infra-common/community-talent-certification-test
  newTag: 7aeb7b63c495e5fe9b9dc11f52d636be1d64810a
