resources:
- namespace.yaml
- ingress.yaml
- service.yaml
- deployment.yaml
- secret.yaml
- autoscaler.yaml
commonAnnotations:
  kubernetes.ops.cluster: test
  kubernetes.ops.email: 15622356989@163.com
  kubernetes.ops.os.base: openeuler
  kubernetes.ops.owner: gongzhuangbang
  kubernetes.ops.region: hk
namespace: community-talent-certification-it-system
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/infra-common/community-talent-certification-test
  newTag: d223a50843822576bb0af12181f1294d2232f94c
