resources:
  - git
  - src-git
  - gitee
  - github
  - website
  - cloudeye
  - maillist
  - namespace.yaml
  - gitee-star
  - collect-data
  - gitee-event
  - cla
  - cloc
  - website-repo
  - website-ru-repo
  - cve
  - polymerization
  - polymerization-download
  - polymerization-download-ip
  - account_org
  - googleanalytic-user
  - gitee-issue
  - gitee-issue-score
  - git_commit
  - up-download-ratio
  - obs_build_averagetime
  - download
  - download_beijing
  - issue_rule_label
  - prophet_prediction
  - user-relation
  - gitee-org-baidutongji
  - git-commit-log
  - code-statistics
  - activities-practice
  - refresh_token
  - rpm-repo-download
  - gitee-metrics
  - sig-score
  - sig-radar-score
  - ndcg
  - company-location
  - github_pr_issue
  - iso_download
  - qinghua-down
  - city-location
  - gitee-repo
  - gitee-pr-version
  - docker-hub
commonAnnotations:
  owner: zhongjun
  email: "jun.zhongjun2@gmail.com"
namespace: openeuler-om
