apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-api
  namespace: chat-api
  labels:
    app: chat-api
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: chat-api
  template:
    metadata:
      labels:
        app: chat-api
    spec:
      containers:
        - name: chat-api
          image: swr.cn-north-4.myhuaweicloud.com/opensourceway/chatapi/chat-api:0.0.1
          resources:
            limits:
              cpu: 2000m
              memory: 16000Mi
              nvidia.com/gpu: 1
            requests:
              cpu: 1000m
              memory: 2000Mi
              nvidia.com/gpu: 1
          volumeMounts:
            - mountPath: /var/lib/om/model/chatglm-6b
              name: chat-api-model-volume
      nodeSelector:
        accelerator: nvidia-t4
      volumes:
        - name: chat-api-model-volume
          persistentVolumeClaim:
            claimName: chat-api-model