resources:
- deployment.yaml
- service.yaml
- secret.yaml
- ingress.yaml
- autoscaler.yaml
commonAnnotations:
  kubernetes.ops.cluster: test
  kubernetes.ops.email: jun.zhongjun2@gmail.com
  kubernetes.ops.os.base: ubuntu
  kubernetes.ops.owner: zhongjun
  kubernetes.ops.region: hk
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openeuler-easyeditor
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/easyeditor/server-test
  newTag: v1.0.20230518103920
