resources:
- namespace.yaml
- ingress.yaml
- service.yaml
- deployment.yaml
- secret.yaml
namespace: openeuler-website
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler-website-test
  newTag: 6003c7b41765828033e076c20ba56806ffaaffd8
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/openeuler-website-portal
  newTag: 5bc8e56f3c40bdd1986183d006c3ea00206f02cf
