resources:
- namespace.yaml
- ingress.yaml
- service.yaml
- deployment.yaml
- secret.yaml
namespace: openeuler-website
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler-website-test
  newTag: ecde49aa73a49584a95a4484d4746dcdc2565cbc
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/openeuler-website-portal
  newTag: 5bc8e56f3c40bdd1986183d006c3ea00206f02cf
