apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  kubernetes.ops.cluster: shanghai-test-cluster
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: openeuler
  kubernetes.ops.owner: chenqi
  kubernetes.ops.region: shanghai
kind: Kustomization
namespace: modelfoundry-usercenter-website
resources:
- namespace.yaml
- website-ingress.yaml
- website-service.yaml
- website-deployment.yaml
- autoscaler.yaml
- secret.yaml
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/gitea/modelfoundry-usercenter-website
  newTag: test-6b3a5f
