resources:
- ingress.yaml
- service.yaml
- deployment.yaml
- autoscaler.yaml
- secret.yaml
- cronjob.yaml
namespace: opengauss-website-revision
commonAnnotations:
  kubernetes.ops.cluster: test
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: openeuler
  kubernetes.ops.owner: liuqi
  kubernetes.ops.region: hk
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.ap-southeast-1.myhuaweicloud.com/infra-hk/openeuler/meetingserver
  newTag: dev_merge_opengauss-f8cb58
