resources:
- namespace.yaml
- ingress.yaml
- service.yaml
- deployment.yaml
- secret.yaml
commonLabels:
  app: openlookeng-website
namespace: openlookeng-website
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/test_openlookeng_website
  newTag: 40085649116466ff67a4b2ed3554792008b31891
