apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-status-handler-deployment
  namespace: openeuler-devops
spec:
  selector:
    matchLabels:
      app: job-status-handler
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/role: 'openeuler-devops'
        vault.hashicorp.com/agent-run-as-user: "1000"
        vault.hashicorp.com/agent-run-as-group: "1000"
        vault.hashicorp.com/secret-volume-path: "/etc/ods/"
        vault.hashicorp.com/agent-inject-secret-secrets.yaml: 'internal/data/infra-test/openeuler-devops'
        vault.hashicorp.com/agent-inject-perms-secrets.yaml: "0400"        
        vault.hashicorp.com/agent-inject-template-secrets.yaml: |  
          {{- with secret "internal/data/infra-test/openeuler-devops" -}}  
          {{ .Data.data.config }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-redisca: 'internal/data/infra-test/openeuler-devops'
        vault.hashicorp.com/agent-inject-perms-redisca: "0400"        
        vault.hashicorp.com/agent-inject-template-redisca: |  
          {{- with secret "internal/data/infra-test/openeuler-devops" -}}  
          {{ .Data.data.redisCA }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-esca: 'internal/data/infra-test/openeuler-devops'
        vault.hashicorp.com/agent-inject-perms-esca: "0400"        
        vault.hashicorp.com/agent-inject-template-esca: |  
          {{- with secret "internal/data/infra-test/openeuler-devops" -}}  
          {{ .Data.data.esCA }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-etcd_client.crt: 'internal/data/infra-test/openeuler-devops'
        vault.hashicorp.com/agent-inject-perms-etcd_client.crt: "0400"
        vault.hashicorp.com/agent-inject-template-etcd_client.crt: |  
          {{- with secret "internal/data/infra-test/openeuler-devops" -}}  
          {{ .Data.data.etcdJobStatusCrt }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-etcd_client.key: 'internal/data/infra-test/openeuler-devops'
        vault.hashicorp.com/agent-inject-perms-etcd_client.key: "0400"
        vault.hashicorp.com/agent-inject-template-etcd_client.key: |  
          {{- with secret "internal/data/infra-test/openeuler-devops" -}}  
          {{ .Data.data.etcdJobStatusKey }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-etcd_ca.crt: 'internal/data/infra-test/openeuler-devops'
        vault.hashicorp.com/agent-inject-perms-etcd_ca.crt: "0400"
        vault.hashicorp.com/agent-inject-template-etcd_ca.crt: |  
          {{- with secret "internal/data/infra-test/openeuler-devops" -}}  
          {{ .Data.data.etcdCA }}
          {{- end }}
      labels:
        app: job-status-handler
    spec:
      serviceAccount: openeuler-devops
      imagePullSecrets:
      - name: huawei-swr-image-pull-secret
      containers:
      - image: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/openeuler-devops/job_status_handler:master-e9f1e3
        imagePullPolicy: IfNotPresent      
        volumeMounts:
        - mountPath: /srv/log
          name: job-status-handler-data-volume
        env:
        - name: LOG_ROOT_DIR
          value: "/srv/log"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name   
        name: job-status-handler
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 500Mi
      volumes:
        - name: job-status-handler-data-volume
          persistentVolumeClaim:
            claimName: job-status-handler-data-volume