apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  kubernetes.ops.cluster: test
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: openeuler
  kubernetes.ops.owner: zhangyizheng
  kubernetes.ops.region: shanghai
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/openeuler-devops/job_status_handler
  newTag: v1.0.20231228191031
kind: Kustomization
namespace: openeuler-devops
resources:
- deployment.yaml
