resources:
- website.yaml
- backend.yaml
- namespace.yaml
- service.yaml
- ingress.yaml
- secret.yaml
- oauth-proxy.yaml
- pvc.yaml
namespace: scan-tools
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/infra-common/scan-tools-backend
  newTag: a923b0f0293cd96536195720a47b59551b683df6
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/infra-common/scan-tools-website
  newTag: a923b0f0293cd96536195720a47b59551b683df6
