resources:
- website.yaml
- backend.yaml
- namespace.yaml
- service.yaml
- ingress.yaml
- secret.yaml
- oauth-proxy.yaml
namespace: scan-tools
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/infra-common/scan-tools-backend
  newTag: e8d9e648c01393e941b4ccd6d078922e81e668f7
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/infra-common/scan-tools-website
  newTag: 5d64587975cffcc96a4ce950882c2d2b6b8acbfc
