resources:
- deployment.yaml
- namespace.yaml
- service.yaml
- ingress.yaml
commonAnnotations:
  kubernetes.ops.cluster: freesky-icsl-hk-cluster
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: debian
  kubernetes.ops.owner: gongzhuangbang
  kubernetes.ops.region: hk
namespace: openlookeng-website
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/icsl/openlookeng-website
  newTag: dfc3b1209c0469027b8aafccbdf6cbf0a734c357
