resources:
- config.yaml
- mailcore.yaml
- mailcoreservice.yaml
- mtaservice.yaml
- namespace.yaml
- nginx-config.yaml
- secrets.yaml
- storage.yaml
- suiteservice.yaml
- webservice.yaml
- ingress.yaml
- maildatabase.yaml
- scan_subscribe_pending.yaml
commonAnnotations:
  email: tommylikehu@gmail.com
  owner: tommylike
namespace: mail
commonLabels:
  solution: control-maillist
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/app-mailman/clean-pending-subscription
  newTag: 5d9e8b1290ae810a1ce8621f5de6c6ccd9d296511677657068
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/app-mailman/mailman-core-new-build
  newTag: 970d27521a1aca24f9e0ff85047f99755ba3af7c1677654154
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/app-mailman/mailman-web-new-build
  newTag: c36771ac3727bcbd3ba32857e44904b7e5c30f321678178659
