# Deployment for icms service
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: icms-hk
  namespace: infra-cve-manager
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: icms
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'icms'
        vault.hashicorp.com/agent-inject-perms-secrets.yaml: "0700"
        vault.hashicorp.com/agent-run-as-user: "1000"
        vault.hashicorp.com/agent-inject-secret-secrets.yaml: 'internal/data/infra-common/infra-cve'
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-inject-template-secrets.yaml: |  
          {{- with secret "internal/data/infra-common/infra-cve" -}}  
          {{ .Data.data.config }}
          {{- end }}
      labels:
        app: icms
    spec:
      imagePullSecrets:
      - name: huawei-swr-image-pull-secret
      serviceAccountName: icms
      containers:
      - name: icms
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/app-icms:17fca54fcfe6df16d8cfae7e67adffcdea0e2ca2
        resources:
          requests:
            cpu: 2000m
            memory: 2000Mi
          limits:
            cpu: 2000m
            memory: 2000Mi
        env:
        - name: TZ
          value: Asia/Shanghai
        - name: CONFIG_PATH
          value: /vault/secrets/secrets.yaml
        volumeMounts:
        - mountPath: /work/icms/cms/migrations
          name: migrations-data
        - mountPath: /work/icms/cms/data
          name: cms-data
        command:
        - /bin/sh
        - -c
        - |
          mkdir -p cms/data/json
          mkdir -p cms/data/repo
          python manage.py collectstatic
          python manage.py makemigrations
          python manage.py migrate
          exec uwsgi --ini /work/icms/deploy/production/uwsgi.ini
      volumes:
      - name: migrations-data
        persistentVolumeClaim:
          claimName: migrations-data-volume
      - name: cms-data
        persistentVolumeClaim:
          claimName: cms-data-volume