resources:
- namespace.yaml
- service.yaml
- deployment.yaml
- autoscaler.yaml
- sa.yaml
namespace: opengauss-website
commonAnnotations:
  kubernetes.ops.cluster: test
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: openeuler
  kubernetes.ops.owner: ailong
  kubernetes.ops.region: hk
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/opengauss/test_opengauss_website
  newName: swr.ap-southeast-1.myhuaweicloud.com/infra-hk/opengauss/test_opengauss_website
  newTag: v2-09abb9
