apiVersion: v1
kind: Service
metadata:
  name: meeting-service
  namespace: mindspore-meetingserver
spec:
  ports:
  - name: http-port
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: meetingserver
  sessionAffinity: None
  type: ClusterIP
