resources:
- deployment.yaml
- secrets.yaml
- ingress.yaml
- service.yaml
- namespace.yaml
namespace: xihe-oneid
commonAnnotations:
  kubernetes.ops.cluster: freesky-icsl-hk-cluster
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: ""
  kubernetes.ops.owner: zhongjun
  kubernetes.ops.region: hk
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/icsl/om-webserver
  newTag: test-pwd-cf524b
