resources:
  - git
  - github
  - website
  - website-ascend
  - gitee
  - download
  - namespace.yaml
  - collect-data
  - gitee-event
  - gitee-star
  - cla
  - polymerization
  - polymerization-download
  - polymerization-download-ip
  - account_org
  - github-star
  - huawei_swr
  - git_commit
  - user-relation
  - gitee-org-baidutongji
  - git-commit-log
  - cve
  - gitee-metrics
  - tinyms_down
  - github_mindspore_pr_issue
  - ndcg
  - activities-practice
  - xihe_down
  - obs-download
  - model-zoo-download
  - gitee-search-repos
  - github-search-repos
  - docker-hub
  - ecosystem-repo
  - sig-maintainer
  - github_mindspore_lab_pr_issue
  - drainage-register
commonAnnotations:
  owner: zhongjun
  email: "jun.zhongjun2@gmail.com"
namespace: mindspore-om
