apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: om-commit-log
  namespace: om
  labels:
    app: om-commit-log
spec:
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app: om-commit-log
    spec:
      containers:
        - name: om-commit-log
          image: swr.cn-north-4.myhuaweicloud.com/om/om-collection:0.4.67
          volumeMounts:
            - mountPath: /var/lib/om/config.ini
              subPath: credentials_cfg
              name: om-commit-log-secrets-volume
            - mountPath: /mnt
              subPath: commitlog
              name: storage
      volumes:
        - name: om-commit-log-secrets-volume
          secret:
            secretName: om-commit-log-secrets
        - name: storage
          persistentVolumeClaim:
            claimName: commitlog
