apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  kubernetes.ops.cluster: test
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: openeuler
  kubernetes.ops.owner: lichaoran
  kubernetes.ops.region: shanghai
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/gitea/merlin-server-test
  newTag: user_api-ae36e0
kind: Kustomization
namespace: merlin
resources:
- server-service.yaml
- server-deployment.yaml
- autoscaler.yaml
