apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: om-gitee-pr-version
  namespace: om
  labels:
    app: om-gitee-pr-version
spec:
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app: om-gitee-pr-version
    spec:
      containers:
        - name: om-gitee-pr-version
          image: swr.cn-north-4.myhuaweicloud.com/om/om-collection:0.5.29
          volumeMounts:
            - mountPath: /var/lib/om/config.ini
              subPath: credentials_cfg
              name: om-gitee-pr-version-secrets-volume
            - mountPath: /mnt
              subPath: giteeprversion
              name: storage
      volumes:
        - name: om-gitee-pr-version-secrets-volume
          secret:
            secretName: om-gitee-pr-version-secrets
        - name: storage
          persistentVolumeClaim:
            claimName: giteeprversion