resources:
- deployment.yaml
- secrets.yaml
- ingress.yaml
- service.yaml
- namespace.yaml
namespace: om-webserver-oneid
commonAnnotations:
  kubernetes.ops.cluster: om-hk-cluster
  kubernetes.ops.email: jun.zhongjun2@gmail.com
  kubernetes.ops.os.base: ""
  kubernetes.ops.owner: zhongjun
  kubernetes.ops.region: hk
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/om/om-webserver
  newName: swr.cn-north-4.myhuaweicloud.com/om/om-webserver-prod
  newTag: test-pwd-8610a0
