apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  kubernetes.ops.cluster: test-cluster
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: ubuntu
  kubernetes.ops.owner: guodaxing
  kubernetes.ops.region: hk
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/openguardfuzz-webserver
  newTag: test-169573
kind: Kustomization
namespace: openguardfuzz-webserver
resources:
- webserver-ingress.yaml
- webserver-service.yaml
- webserver-secret.yaml
- webserver-pvc-0.yaml
- webserver-deployment.yaml
- autoscaler.yaml
