apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  kubernetes.ops.cluster: test-cluster
  kubernetes.ops.community: libing
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: openeuler
  kubernetes.ops.owner: niexinquan
  kubernetes.ops.region: hk
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/cache-proxy-test
  newTag: wenhao7-6fbeae
kind: Kustomization
namespace: openeuler-cache-proxy
resources:
- namespace.yaml
- server-ingress.yaml
- server-service.yaml
- server-deployment.yaml
- autoscaler.yaml
- pvc.yaml
- secret.yaml
