---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-issuer
  name: opendesign-datapertus-test-openeuler-ingress
  namespace: opendesign-datapertus-test
spec:
  tls:
    - hosts:
        - datastatopeneuler.test.osinfra.cn
      secretName: opendesign-datapertus-test-openeuler-tls
  rules:
    - host: datastatopeneuler.test.osinfra.cn
      http:
        paths:
          - backend:
              serviceName: opendesign-datapertus-test-service
              servicePort: 80
            path: /

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-issuer
  name: opendesign-datapertus-test-mindspore-ingress
  namespace: opendesign-datapertus-test
spec:
  tls:
    - hosts:
        - datastatmindspore.test.osinfra.cn
      secretName: opendesign-datapertus-test-mindspore-tls
  rules:
    - host: datastatmindspore.test.osinfra.cn
      http:
        paths:
          - backend:
              serviceName: opendesign-datapertus-test-service
              servicePort: 80
            path: /

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-issuer
  name: opendesign-datapertus-test-opengauss-ingress
  namespace: opendesign-datapertus-test
spec:
  tls:
    - hosts:
        - datastatopengauss.test.osinfra.cn
      secretName: opendesign-datapertus-test-opengauss-tls
  rules:
    - host: datastatopengauss.test.osinfra.cn
      http:
        paths:
          - backend:
              serviceName: opendesign-datapertus-test-service
              servicePort: 80
            path: /

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-issuer
  name: opendesign-datapertus-test-openlookeng-ingress
  namespace: opendesign-datapertus-test
spec:
  tls:
    - hosts:
        - datastatopenlookeng.test.osinfra.cn
      secretName: opendesign-datapertus-test-openlookeng-tls
  rules:
    - host: datastatopenlookeng.test.osinfra.cn
      http:
        paths:
          - backend:
              serviceName: opendesign-datapertus-test-service
              servicePort: 80
            path: /