resources:
- deployment.yaml
- namespace.yaml
- service.yaml
- ingress.yaml
namespace: opendesign-datapertus-test
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/dataset-test
  newName: swr.cn-north-4.myhuaweicloud.com/opensourceway/dataset-test
  newTag: 91bb877e771be513890c7a0cc32fb9ef28ceb28e
