resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- secrets.yaml
- ingress.yaml
- pvc.yaml
- autoscaler.yaml
commonAnnotations:
  kubernetes.ops.cluster: test
  kubernetes.ops.email: 747802914@qq.com
  kubernetes.ops.os.base: debian
  kubernetes.ops.owner: liuyang
  kubernetes.ops.region: hk
namespace: etherpad
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/etherpad
  newTag: 1.8.18
