resources:
- namespace.yaml
- ingress.yaml
- service.yaml
- deployment.yaml
- secret.yaml
- pvc.yaml
- autoscaler.yaml
commonAnnotations:
  kubernetes.ops.cluster: test
  kubernetes.ops.email: openlibing@163.com
  kubernetes.ops.os.base: openeuler
  kubernetes.ops.owner: zhangyaxiong
  kubernetes.ops.region: hk
namespace: majun-anti-poisoning
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/majun/anti-poisoning-test
  newTag: ef65300d936be0482104c0d1745956354c7f04b2
