resources:
- deployment.yaml
- autoscaler.yaml
commonAnnotations:
  kubernetes.ops.cluster: test
  kubernetes.ops.email: 377075038@qq.com
  kubernetes.ops.os.base: openeuler
  kubernetes.ops.owner: wangdi
  kubernetes.ops.region: hk
namespace: radia-test-beta
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/radia-test/periodic-worker-beta
  newTag: v1.0.20230403195156
