apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/cors-allow-credentials: "false"
    nginx.ingress.kubernetes.io/server-snippet: |
      location ^~ /admin {
        deny all;
      }
      location ^~ /stats {
        deny all;
      }
  name: openlookeng-ingress
  namespace: openlookeng-etherpad
spec:
  rules:
  - host: etherpad.openlookeng.io
    http:
      paths:
      - backend:
          serviceName: etherpad-lite-v2
          servicePort: 9001
        path: /
  tls:
  - hosts:
    - etherpad.openlookeng.io
    secretName: etherpad-openlookeng-tls
