resources:
- namespace.yaml
- pvc.yaml
- secret.yaml
- website
- casefile-resolver
- celerybeat
- database-updator
- gunicorn
- issuerate-updator
- openqa-reader
- periodic-worker
- root-resolver
- scripts-loader
- rabbitmq
namespace: radia-test-beta
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
