apiVersion: v1
kind: Service
metadata:
  name: om-webserver-service
  namespace: om-webserver-test
spec:
  ports:
    - name: srv
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: om-webserver
  type: ClusterIP
