resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- secrets.yaml
- ingress.yaml
commonLabels:
  app: cve-manager
  owner: zhaojiaming
commonAnnotations:
  owner: zhaojiaming
namespace: cve-manager
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/cve-manager-test
  newTag: f54723014599336d58657e650ce686dbb2a8cfab
