resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- secrets.yaml
- ingress.yaml
- autoscaler.yaml
commonLabels:
  app: cve-manager
  owner: zhaojiaming
commonAnnotations:
  kubernetes.ops.cluster: test
  kubernetes.ops.email: zjm.514@qq.com
  kubernetes.ops.os.base: openeuler
  kubernetes.ops.owner: zhaojiaming
  kubernetes.ops.region: hk
namespace: cve-manager
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/cve-manager-test
  newTag: 17936e836a6a2806ff9b3babfdebfb0c21552068
