---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: doc-search
  namespace: openeuler-doc-search
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: doc-search
  template:
    metadata:
      labels:
        app: doc-search
    spec:
      nodeSelector:
        autoscaler: "true"
      imagePullSecrets:
      - name: huawei-swr-image-pull-secret
      containers:
      - name: doc-search
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/doc-search-test:19998e269f5c6a35c6fc106887d80d0d3b773942
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
          limits:
            cpu: 1000m
            memory: 3000Mi
        env:
        - name: eshost
          valueFrom:
            secretKeyRef:
              name: doc-search-secrets
              key: host
        - name: esusername
          valueFrom:
            secretKeyRef:
              name: doc-search-secrets
              key: username
        - name: espassword
          valueFrom:
            secretKeyRef:
              name: doc-search-secrets
              key: password
        - name: esport
          valueFrom:
            secretKeyRef:
              name: doc-search-secrets
              key: port
        - name: searchsystem
          valueFrom:
            secretKeyRef:
              name: doc-search-secrets
              key: system
        - name: teshost
          valueFrom:
            secretKeyRef:
              name: doc-search-secrets
              key: teshost
        - name: tesusername
          valueFrom:
            secretKeyRef:
              name: doc-search-secrets
              key: tesusername
        - name: tesport
          valueFrom:
            secretKeyRef:
              name: doc-search-secrets
              key: tesport
        - name: tespassword
          valueFrom:
            secretKeyRef:
              name: doc-search-secrets
              key: tespassword
        - name: kneed
          valueFrom:
            secretKeyRef:
              name: doc-search-secrets
              key: kneed
        - name: kbootstrap
          valueFrom:
            secretKeyRef:
              name: doc-search-secrets
              key: kbootstrap
        - name: kgroup
          valueFrom:
            secretKeyRef:
              name: doc-search-secrets
              key: kgroup
        - name: GIT_USERNAME
          valueFrom:
            secretKeyRef:
              name: doc-search-secrets
              key: GIT_USERNAME
        - name: GIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: doc-search-secrets
              key: GIT_PASSWORD

