# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sca-gateway
  namespace: sca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sca-gateway
  template:
    metadata:
      labels:
        app: sca-gateway
    spec:
      imagePullSecrets:
        - name: huawei-swr-image-pull-secret
      containers:
      - name: sca-gateway
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/icsl/sca-gateway:801778e1457c511da1add445cb045a0c5d909fd8
        imagePullPolicy: IfNotPresent
        ports:
        - name: app-port
          containerPort: 8015
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: SERVICE_NAME
            value: utralsca-gateway
          - name: EUREKA_SERVER
            value: "http://eureka.sca.svc.cluster.local:9000/eureka"
          - name: APP_ENV
            value: acceptance
          - name: PACKAGE_VERSION
            value: 1.0-SNAPSHOT
          - name: MAX_HEAP_MEM
            value: 3072m
          - name: INIT_HEAP_MEM
            value: 512m
          - name: CMS_IOF
            value: "75"
          - name: INIT_KEY
            valueFrom:
              secretKeyRef:
                name: sca-secret
                key: app-init-key
          - name: jasypt.encryptor.algorithm
            valueFrom:
              secretKeyRef:
                name: sca-secret
                key: jasypt_encryptor_algorithm
          - name: jasypt.encryptor.password
            valueFrom:
              secretKeyRef:
                name: sca-secret
                key: jasypt_encryptor_password
          - name: jasypt_password
            valueFrom:
              secretKeyRef:
                name: sca-secret
                key: jasypt_encryptor_password
          - name: majun.access.token
            valueFrom:
              secretKeyRef:
                name: sca-secret
                key: majun_access_token
        resources:
          requests:
            cpu: 200m
            memory: 1024Mi
          limits:
            cpu: 800m
            memory: 2G

