resources:
- ingress.yaml
- configmap.yaml
- deployment.yaml
- service.yaml
- secret.yaml
- autoscaler.yaml
namespace: opendesign-datapertus-test
commonAnnotations:
  kubernetes.ops.cluster: test
  kubernetes.ops.email: 2915341988@qq.com
  kubernetes.ops.os.base: debian
  kubernetes.ops.owner: yuchunao
  kubernetes.ops.region: hk
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/datastat/openeuler-test
  newTag: 2ac56e65ee772c0f956bb335c0a6dd40afcb9a52
