apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: internship-ingress
  namespace: mindspore-internship
spec:
  tls:
    - hosts:
        - new.mindspore.myopeninfra.com
      secretName: internship-tls
  rules:
    - host: new.mindspore.myopeninfra.com
      http:
        paths:
          - backend:
              serviceName: internship-service
              servicePort: 80
            path: /
