resources:
- service.yaml
- deployment.yaml
- autoscaler.yaml
namespace: openeuler-signatrust
commonAnnotations:
  kubernetes.ops.cluster: test
  kubernetes.ops.email: tommylikehu@gmail.com
  kubernetes.ops.os.base: alpine
  kubernetes.ops.owner: husheng
  kubernetes.ops.region: hk
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/signatrust/signatrust-control-server
  newTag: d77c3fff90ae5d142ccb109f43388079710f4579
