apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  kubernetes.ops.cluster: test-cluster
  kubernetes.ops.email: ''
  kubernetes.ops.os.base: openeuler
  kubernetes.ops.owner: chenyang
  kubernetes.ops.region: hk
kind: Kustomization
namespace: mindspore-website2
resources:
- autoscaler.yaml
- backend-ingress.yaml
- backend-service.yaml
- backend-secret.yaml
- backend-deployment.yaml
