---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: sbom-deployment
  namespace: openeuler-sbom-service
spec:
  selector:
    matchLabels:
      app: sbom-deployment
  template:
    metadata:
      labels:
        app: sbom-deployment
    spec:
      imagePullSecrets:
        - name: huawei-swr-image-pull-secret
      containers:
      - name: sbom-service
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/openeuler-sbom-service-test:0bc3b1e0704882bb631bd778f9939439569b26b0
        resources:
          requests:
            cpu: 4000m
            memory: 8000Mi
          limits:
            cpu: 4000m
            memory: 8000Mi
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              key: db_host
              name: sbom-server-secrets
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              key: db_port
              name: sbom-server-secrets
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              key: db_name
              name: sbom-server-secrets
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: db_username
              name: sbom-server-secrets
        - name: DB_PASSWORD_FILE
          valueFrom:
            secretKeyRef:
              key: db_password_file
              name: sbom-server-secrets
        - name: OSSINDEX_API_TOKEN_FILE
          valueFrom:
            secretKeyRef:
              key: ossindex_api_token_file
              name: sbom-server-secrets
        - name: GITHUB_API_TOKEN_FILE
          valueFrom:
            secretKeyRef:
              key: github_api_token_file
              name: sbom-server-secrets
        - name: GITEE_API_TOKEN_FILE
          valueFrom:
            secretKeyRef:
              key: gitee_api_token_file
              name: sbom-server-secrets
        - name: GITLAB_API_TOKEN_FILE
          valueFrom:
            secretKeyRef:
              key: gitlab_api_token_file
              name: sbom-server-secrets
        volumeMounts:
        - mountPath: /var/db_secrets
          name: db-secret
      volumes:
      - name: db-secret
        secret:
          secretName: sbom-server-db-secrets
        
          



