resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- secrets.yaml
- ingress.yaml
- sbom-website.yaml
- sbom-repo-service.yaml
- repo-post-verify.yaml
commonAnnotations:
  email: huangheqing2@huawei.com
  owner: huangheqing
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openeuler-sbom-service
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/openeuler-sbom-service-test
  newTag: 1e6de9df5d118d25ee4699d79dc5e693334b73f2
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/openeuler-sbom-website-test
  newTag: v1.0.20220928145953
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/repo-post-verification-test
  newTag: e1970dd51acecc9bea78d0fbade7ca3f1423b6e7
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/sbom-repo-service
  newTag: v1.0.20221018154922
