resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- secrets.yaml
- ingress.yaml
- sbom-website.yaml
- sbom-repo-service.yaml
- repo-post-verify.yaml
- pvc.yaml
- autoscaler.yaml
commonAnnotations:
  kubernetes.ops.cluster: test
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: alpine
  kubernetes.ops.owner: huangheqing
  kubernetes.ops.region: hk
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openeuler-sbom-service
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/openeuler-sbom-service-test
  newTag: v1.0.20230905151139
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/openeuler-sbom-website-test
  newTag: v1.0.20231110191003
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/repo-post-verification-test
  newTag: 6ea300b29b3bd2d76a5276f6ac8886058cd9ee7f
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/sbom-repo-service
  newTag: v1.0.20221108210256
