resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- secrets.yaml
- ingress.yaml
- sbom-website.yaml
- sbom-repo-service.yaml
- repo-post-verify.yaml
- autoscaler.yaml
commonAnnotations:
  kubernetes.ops.cluster: test
  kubernetes.ops.email: huangheqing2@huawei.com
  kubernetes.ops.os.base: alpine
  kubernetes.ops.owner: huangheqing
  kubernetes.ops.region: hk
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openeuler-sbom-service
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/openeuler-sbom-service-test
  newTag: v1.0.20230630101521
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/openeuler-sbom-website-test
  newTag: v1.0.20230630100916
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/repo-post-verification-test
  newTag: b664f531ba92c5cf14cff0391d6ac74271f3095e
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/sbom-repo-service
  newTag: v1.0.20221108210256
