apiVersion: v1
kind: ConfigMap
metadata:
  name: git-metadata-config
data:
  app.toml: |
    name = "community-metadata"
    timezone = "PRC"
    httpPort = 9500

    [log]
    logFile = "/app/logs/run-application-{date}.log"
    errFile = "/app/logs/run-error-{date}.log"

    [manager]
    syncInterval = 30
    notifyInterval = 30
    baseFolder = "/app/repos/"
    gitSyncPath = "/app/git-sync"

    [plugins.playgroundmeta]
    enabled = true
