---
apiVersion: v1
kind: ConfigMap
metadata:
  name: github-cla-repo
  namespace: cla
data:
  cla-repo.yaml: |
    cla:
    - repos:
      - openlookeng
      cla_label_yes: openlookeng-cla/yes
      cla_label_no: openlookeng-cla/no
      cla_id: "gitee_openlookeng-1614322910578209320"
      sign_url: "https://clasign.openlookeng.io/sign"
      check_by_committer: false