resources:
- deployment.yaml
- service.yaml
- configmap.yaml
commonAnnotations:
  kubernetes.ops.cluster: openeuler-hk
  kubernetes.ops.email: chenzeng765@163.com
  kubernetes.ops.os.base: debian
  kubernetes.ops.owner: chenzeng
  kubernetes.ops.region: hk
namespace: cla
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/cla-robot
  newTag: b24aee5c1a3be0d35369361b68309a9fa5fb8a6b
