resources:
- namespace.yaml
- ingress.yaml
- service.yaml
- deployment.yaml
- secret.yaml
- pvc.yaml
namespace: majun-anti-poisoning
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/majun/anti-poisoning
  newTag: 7fa051cbd6e2b64cf68dd9a0aab17d88249593c5
