apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: anti-poisoning-ingress
  namespace: majun-anti-poisoning
spec:
  tls:
    - hosts:
        - anti-poison.test.osinfra.cn
      secretName: anti-poisoning-tls
  rules:
    - host: anti-poison.test.osinfra.cn
      http:
        paths:
          - backend:
              serviceName: anti-poisoning-service
              servicePort: 80
            path: /
