apiVersion: v1
kind: Service
metadata:
  name: gitea-repo
  namespace: gitea-repo
spec:
  ports:
  - name: https-port
    protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    app: gitea-repo
  type: ClusterIP

  
