apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/server-snippet: |
      location ^~ /meetings/participants/ {
        deny all;
      }
  name: meeting-ingress
  namespace: mindspore-meetingserver
spec:
  rules:
  - host: meeting.mindspore.myopeninfra.com
    http:
      paths:
      - backend:
          serviceName: meeting-service
          servicePort: 80
        path: /meetings(/|$)(.*)
  tls:
  - hosts:
    - meeting.mindspore.myopeninfra.com
    secretName: website-tls
