apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  kubernetes.ops.cluster: test
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: openeuler
  kubernetes.ops.owner: yangwei
  kubernetes.ops.region: hk
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/software-package-watch-test
  newTag: dev_watch-d9d6fe
kind: Kustomization
namespace: openeuler-software-pkg
resources:
- server-deployment.yaml
- autoscaler.yaml
- configmap.yaml
