---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xihe-script
  namespace: xihe-test-v2
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: xihe-script
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-perms-application.yml: "0600"
        vault.hashicorp.com/agent-inject-perms-mq.crt: "0600"
        vault.hashicorp.com/agent-run-as-user: "5000"
        vault.hashicorp.com/agent-inject-secret-application.yml: xihe/data/conf
        vault.hashicorp.com/agent-inject-template-application.yml: |
          {{- with secret "xihe/data/conf/" -}}
          {{ .Data.data.xiheScript }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-mq.crt: xihe/data/conf/
        vault.hashicorp.com/agent-inject-template-mq.crt: |
          {{- with secret "xihe/data/conf/" -}}
          {{ .Data.data.MqCA }}
          {{- end }}
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/role: xihe-test
      labels:
        app: xihe-script
    spec:
      serviceAccount: xihe-test
      imagePullSecrets:
      - name: huawei-swr-image-pull-secret
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      tolerations:
      - key: "icsl"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      containers:
      - name: xihe-script
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/mindspore/xihe-script:v1.0.20221122113307
        imagePullPolicy: IfNotPresent
        args:
        - --config-file=/vault/secrets/application.yml
        resources:
          requests:
            cpu: 2000m
            memory: 2000Mi
          limits:
            cpu: 2000m
            memory: 4000Mi
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 1Gi