resources:
- namespace.yaml
- ingress.yaml
- service.yaml
- deployment.yaml
- autoscaler.yaml
namespace: openeuler-new-feature
commonAnnotations:
  kubernetes.ops.cluster: test
  kubernetes.ops.email: 845831435@qq.com
  kubernetes.ops.os.base: debian
  kubernetes.ops.owner: wangxing
  kubernetes.ops.region: hk
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/openeuler-quickissue-test
  newTag: 74778d4bf5b9dd72cf1544c24285a9cdd0760350
