apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: xihe-test-v2
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      component: training-center-huaweicloud
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-perms-application.yml: "0700"
        vault.hashicorp.com/agent-run-as-user: "5000"
        vault.hashicorp.com/agent-inject-secret-application.yml: xihe/data/conf
        vault.hashicorp.com/agent-inject-template-application.yml: |
          {{- with secret "xihe/data/conf/" -}}
          {{ .Data.data.training }}
          {{- end }}
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/role: xihe-test
      labels:
        component: training-center-huaweicloud
    spec:
      serviceAccount: xihe-test
      imagePullSecrets:
      - name: huawei-swr-image-pull-secret
      containers:
      - name: training-center-huaweicloud
        args:
        - --port=8000
        - --config-file=/vault/secrets/application.yml
        - --enable_debug=false
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
