apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  kubernetes.ops.cluster: test-cluster
  kubernetes.ops.email: 775517776@qq.com
  kubernetes.ops.os.base: debian
  kubernetes.ops.owner: chenyang
  kubernetes.ops.region: hk
kind: Kustomization
namespace: mindspore-website2
resources:
- website-ingress.yaml
- website-service.yaml
- website-secret.yaml
- website-deployment.yaml
- pvc.yaml
- autoscaler.yaml
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/mindspore/website
  newTag: v1.0.20230625180913
