---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openeuler-website-docs-zh
  namespace: openeuler-website-docs
spec:
  selector:
    matchLabels:
      app: openeuler-website-docs-zh
  template:
    metadata:
      labels:
        app: openeuler-website-docs-zh
    spec:
      imagePullSecrets:
      - name: huawei-swr-image-pull-secret
      containers:
      - name: openeuler-website-docs-zh
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/openeuler-website-docs-zh-test:32b1c22e9f4e5d88baf89c01270280e9b61a7ff1 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
          limits:
            cpu: 500m
            memory: 500Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openeuler-website-docs-ru
  namespace: openeuler-website-docs
spec:
  selector:
    matchLabels:
      app: openeuler-website-docs-ru
  template:
    metadata:
      labels:
        app: openeuler-website-docs-ru
    spec:
      imagePullSecrets:
      - name: huawei-swr-image-pull-secret
      containers:
      - name: openeuler-website-docs-ru
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/openeuler-website-docs-ru-test:32b1c22e9f4e5d88baf89c01270280e9b61a7ff1 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
          limits:
            cpu: 500m
            memory: 500Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openeuler-website-docs-preview
  namespace: openeuler-website-docs
spec:
  selector:
    matchLabels:
      app: openeuler-website-docs-preview
  template:
    metadata:
      labels:
        app: openeuler-website-docs-preview
    spec:
      imagePullSecrets:
      - name: huawei-swr-image-pull-secret
      containers:
      - name: docs
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/website-docs-preview:v1.0.20230117113908 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
          limits:
            cpu: 500m
            memory: 500Mi
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 80
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 80
          timeoutSeconds: 5
