apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- ingress.yaml
- service.yaml
- secret.yaml
commonAnnotations:
  kubernetes.ops.cluster: test
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: openeuler
  kubernetes.ops.owner: wurongqiang
  kubernetes.ops.region: hk
namespace: unified-vulnerability-platform
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/uvp-test
  newTag: v1.0.20231226085008
