apiVersion: apps/v1
kind: Deployment
metadata:
  name: datastat-server
  namespace: datastat-server
  labels:
    app: datastat-server
spec:
  replicas: 2
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app: datastat-server
    spec:
      imagePullSecrets:
      - name: huawei-swr-image-pull-secret
      containers:
        - name: datastat-server
          image: swr.cn-north-4.myhuaweicloud.com/om/ds:0.0.45
          resources:
            limits:
              cpu: 2000m
              memory: 8000Mi
            requests:
              cpu: 1000m
              memory: 5000Mi
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8888
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8888
            timeoutSeconds: 5
          ports:
            - containerPort: 8888
              name: datastat-server
          volumeMounts:
            - mountPath: /var/lib/ds/custom.properties
              subPath: custom_properties
              name: datastat-server-secrets-volume
            - mountPath: /var/lib/ds/openEuler.properties
              subPath: openEuler_properties
              name: datastat-server-secrets-volume
            - mountPath: /var/lib/ds/openGauss.properties
              subPath: openGauss_properties
              name: datastat-server-secrets-volume
            - mountPath: /var/lib/ds/openLookeng.properties
              subPath: openLookeng_properties
              name: datastat-server-secrets-volume
            - mountPath: /var/lib/ds/mindSpore.properties
              subPath: mindSpore_properties
              name: datastat-server-secrets-volume
            - mountPath: /var/lib/ds/application.properties
              subPath: application_properties
              name: datastat-server-secrets-volume
      volumes:
        - name: datastat-server-secrets-volume
          secret:
            secretName: datastat-server-secrets
