apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/limit-connections: "400"
    nginx.ingress.kubernetes.io/limit-rps: "400"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($http_origin ~* "^https?://((?:.*\.test\.osinfra\.cn)|(?:.*\.omapi\.osinfra\.cn)|(?:.*\.mindspore\.cn)|(?:.*\.opengauss\.org))$") {
        set $cors "true";
      }
      if ($http_origin ~* "^https?://((?:.*\.openeuler\.org)|(?:.*\.openlookeng\.io))$") {
        set $cors "true";
      }
      if ($http_origin ~* "^https?://(mindspore\.cn)$") {
        set $cors "true";
      }
      if ($http_origin ~ '^http:\/\/localhost:45678$') {
        set $cors "true";
      }
      if ($http_origin ~ '^http:\/\/114\.116\.235\.161$') {
        set $cors "true";
      }
      if ($request_method = 'OPTIONS') {
        set $cors "${cors}options";
      }
      if ($cors = "true") {
        add_header 'Access-Control-Allow-Origin' "$http_origin" always;
        add_header 'Access-Control-Allow-Methods' 'GET, PUT, POST, DELETE, PATCH, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization' always;
        add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range' always;
      }
      if ($cors = "trueoptions") {
        add_header 'Access-Control-Allow-Origin' "$http_origin";
        add_header 'Access-Control-Allow-Methods' 'GET, PUT, POST, DELETE, PATCH, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization';
        add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
        add_header 'Access-Control-Max-Age' 1728000;
        add_header 'Content-Type' 'text/plain charset=UTF-8';
        add_header 'Content-Length' 0;
        return 204;
      }
  name: datastat-server-ingress
spec:
  tls:
    - hosts:
        - dsapi.osinfra.cn
      secretName: tls-secrets
  rules:
    - host: dsapi.osinfra.cn
      http:
        paths:
          - backend:
              serviceName: datastat-server-service
              servicePort: 80
            path: /
