apiVersion: apps/v1
kind: Deployment
metadata:
  name: pods-monitor-deployment
  namespace: openeuler-devops
spec:
  selector:
    matchLabels:
      app: pods-monitor
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/role: 'openeuler-devops'
        vault.hashicorp.com/agent-run-as-user: "1000"
        vault.hashicorp.com/agent-run-as-group: "1000"
        vault.hashicorp.com/secret-volume-path: "/etc/ods/"
        vault.hashicorp.com/agent-inject-secret-secrets.yaml: 'internal/data/infra-test/openeuler-devops'
        vault.hashicorp.com/agent-inject-perms-secrets.yaml: "0400"        
        vault.hashicorp.com/agent-inject-template-secrets.yaml: |  
          {{- with secret "internal/data/infra-test/openeuler-devops" -}}  
          {{ .Data.data.config }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-openeuler-devops.conf: 'internal/data/infra-test/openeuler-devops'
        vault.hashicorp.com/agent-inject-perms-openeuler-devops.conf: "0400"        
        vault.hashicorp.com/agent-inject-template-openeuler-devops.conf: |  
          {{- with secret "internal/data/infra-test/openeuler-devops" -}}  
          {{ .Data.data.kubeconfig }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-etcd_client.crt: 'internal/data/infra-test/openeuler-devops'
        vault.hashicorp.com/agent-inject-perms-etcd_client.crt: "0400"
        vault.hashicorp.com/agent-inject-template-etcd_client.crt: |  
          {{- with secret "internal/data/infra-test/openeuler-devops" -}}  
          {{ .Data.data.etcdPodsMonitorCrt }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-etcd_client.key: 'internal/data/infra-test/openeuler-devops'
        vault.hashicorp.com/agent-inject-perms-etcd_client.key: "0400"
        vault.hashicorp.com/agent-inject-template-etcd_client.key: |  
          {{- with secret "internal/data/infra-test/openeuler-devops" -}}  
          {{ .Data.data.etcdPodsMonitorKey }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-etcd_ca.crt: 'internal/data/infra-test/openeuler-devops'
        vault.hashicorp.com/agent-inject-perms-etcd_ca.crt: "0400"
        vault.hashicorp.com/agent-inject-template-etcd_ca.crt: |  
          {{- with secret "internal/data/infra-test/openeuler-devops" -}}  
          {{ .Data.data.etcdCA }}
          {{- end }}
      labels:
        app: pods-monitor
    spec:
      serviceAccount: openeuler-devops
      imagePullSecrets:
      - name: huawei-swr-image-pull-secret
      containers:
      - image: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/openeuler-devops/pods_monitor:new
        imagePullPolicy: IfNotPresent
        name: pods-monitor
        env:
        - name: SECRETS_CONFIG
          value: "/etc/ods/secrets.yaml"
        - name: KUBE_CONFIG
          value: "/etc/ods/openeuler-devops.conf"
        - name: KUBE_NAMESPACE
          value: "openeuler-devops"
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 500Mi