---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mindspore-website
  namespace: mindspore-website
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: mindsporewebsite
  template:
    metadata:
      labels:
        app: mindsporewebsite
    spec:
      containers:
      - name: website
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/icsl/mindspore-website:v1.0.20230612110208
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
          - name: MS_MYSQL_URL
            value: jdbc:mysql://172.16.100.48:3306/website?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
          - name: MS_MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: mysql_password
                name: website-secrets
          - name: MS_MAIL_URL
            value: mail.mindspore.cn
          - name: MS_MAIL_NAME
            value: news@mindspore.cn
          - name: MS_MAIL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: mail_password
                name: website-secrets
          - name: RASP_TENANTID
            valueFrom:
              secretKeyRef:
                key: rasp_tenantid
                name: website-secrets
          - name: RASP_APPID
            valueFrom:
              secretKeyRef:
                key: rasp_appid
                name: website-secrets
          - name: RASP_SECRET
            valueFrom:
              secretKeyRef:
                key: rasp_secret
                name: website-secrets
          - name: MS_REDIS_HOST
            value: 172.16.100.93
          - name: MS_REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                key: redis_password
                name: website-secrets
          - name: MS_REDIS_PORT
            valueFrom:
              secretKeyRef:
                key: redis_port
                name: website-secrets
          - name: MS_PYTORCH_URL
            valueFrom:
              secretKeyRef:
                key: pytorch_url
                name: website-secrets
        resources:
          requests:
            cpu: 2000m
            memory: 2000Mi
          limits:
            cpu: 2000m
            memory: 2000Mi
        volumeMounts:
          - mountPath: /mnt/share/file
            name: website-data-volume
          - mountPath: /mnt/share/mindspore_repository
            name: website-hub-data-volume
      volumes:
        - name: website-data-volume
          persistentVolumeClaim:
            claimName: website-data
        - name: website-hub-data-volume
          persistentVolumeClaim:
            claimName: website-hub-data
