apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/server-snippet: |
      rewrite ^~/resource/ https://gitee.com/mindspore/book redirect;
      rewrite ^/icla https://clasign.osinfra.cn/sign/Z2l0ZWUlMkZtaW5kc3BvcmU= redirect;
      rewrite ^/mindinsight$              https://mindspore.myopeninfra.com/mindinsight/docs/zh-CN/master/index.html   redirect;
      rewrite ^/mindinsight/en(/|$)(.*)   https://mindspore.myopeninfra.com/mindinsight/docs/en/master/index.html      redirect;
      rewrite ^/hub$                      https://mindspore.myopeninfra.com/hub/docs/zh-CN/master/index.html           redirect;
      rewrite ^/hub/en(/|$)(.*)           https://mindspore.myopeninfra.com/hub/docs/en/master/index.html              redirect;
      rewrite ^/mindarmour$               https://mindspore.myopeninfra.com/mindarmour/docs/zh-CN/master/index.html    redirect;
      rewrite ^/mindarmour/en(/|$)(.*)    https://mindspore.myopeninfra.com/mindarmour/docs/en/master/index.html       redirect;
      rewrite ^/federated$                https://mindspore.myopeninfra.com/federated/docs/zh-CN/master/index.html     redirect;
      rewrite ^/federated/en(/|$)(.*)     https://mindspore.myopeninfra.com/federated/docs/en/master/index.html        redirect;
      rewrite ^/serving$                  https://mindspore.myopeninfra.com/serving/docs/zh-CN/master/index.html       redirect;
      rewrite ^/serving/en(/|$)(.*)       https://mindspore.myopeninfra.com/serving/docs/en/master/index.html          redirect;
      rewrite ^/probability$              https://mindspore.myopeninfra.com/probability/docs/zh-CN/master/index.html   redirect;
      rewrite ^/probability/en(/|$)(.*)   https://mindspore.myopeninfra.com/probability/docs/en/master/index.html      redirect;
      rewrite ^/mindquantum$              https://mindspore.myopeninfra.com/mindquantum/docs/zh-CN/master/index.html   redirect;
      rewrite ^/mindquantum/en(/|$)(.*)   https://mindspore.myopeninfra.com/mindquantum/docs/en/master/index.html      redirect;
      rewrite ^/reinforcement$            https://mindspore.myopeninfra.com/reinforcement/docs/zh-CN/master/index.html redirect;
      rewrite ^/reinforcement/en(/|$)(.*) https://mindspore.myopeninfra.com/reinforcement/docs/en/master/index.html    redirect;
      rewrite ^/docs/api/(.*)/master/(.*) https://mindspore.myopeninfra.com/docs/$1/master/$2                          redirect;
    nginx.ingress.kubernetes.io/proxy-body-size: 1024m
    nginx.ingress.kubernetes.io/custom-http-errors: '400,500,404'
  name: website-ingress
  namespace: mindspore-website
spec:
  tls:
    - hosts:
        - mindspore.myopeninfra.com
      secretName: website-tls
  rules:
    - host: mindspore.myopeninfra.com
      http:
        paths:
          - backend:
              serviceName: websiteservice
              servicePort: 80
            path: /
          - backend:
              serviceName: websiteservice
              servicePort: 80
            path: /robots.txt
