apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- ingress.yaml
- secrets.yaml
- service.yaml
- namespace.yaml
- pvc.yaml
- cronjob.yaml
- autoscaler.yaml
commonAnnotations:
  kubernetes.ops.cluster: test
  kubernetes.ops.email: shalldows@163.com
  kubernetes.ops.os.base: ubuntu
  kubernetes.ops.owner: wanghao
  kubernetes.ops.region: hk
namespace: patchwork
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/patchwork/patchwork
  newTag: test-a34d7a0
