resources:
  - obs-job-history
  - obs-job-history-recent
  - obs-status-summary
  - statewall-ci-ac
  - namespace.yaml
  - statewall-dist-build-time
  - package-status
  - statewall-ci-result
  - statewall-ci-mistake
  - community-tracker
  - user-apply
commonAnnotations:
  owner: zhongjun
  email: "jun.zhongjun2@gmail.com"
namespace: openeuler-kafka
