apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  kubernetes.ops.cluster: test
  kubernetes.ops.email: 845831435@qq.com
  kubernetes.ops.os.base: debian
  kubernetes.ops.owner: wangxing
  kubernetes.ops.region: hk
namespace: community-summary
resources:
- openeuler-summary-deployment.yaml
- openeuler-summary-ingress.yaml
- openeuler-summary-service.yaml
- oauth-proxy.yaml
- autoscaler.yaml
