apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: opengauss-meeting-server-ingress
  namespace: opengauss-website
spec:
  tls:
    - hosts:
        - opengauss.myopeninfra.com
      secretName: meeting-server-tls
  rules:
    - host: opengauss.myopeninfra.com
      http:
        paths:
          - backend:
              serviceName: meeting-service
              servicePort: 80
            path: /calendar(/|$)(.*)