resources:
- deployment.yaml
- namespace.yaml
- service.yaml
- ingress.yaml
namespace: cvesa-test
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/cve-sa-backend/cvesa-test
  newName: swr.cn-north-4.myhuaweicloud.com/opensourceway/cve-sa-backend/cvesa-test
  newTag: 110da36ac242feb99752fc1d122795412d6de4d9
