resources:
- namespace.yaml
- ingress.yaml
- service.yaml
- deployment.yaml
- autoscaler.yaml
commonAnnotations:
  kubernetes.ops.cluster: test
  kubernetes.ops.email: duyiwei@kylinos.cn
  kubernetes.ops.os.base: openeuler
  kubernetes.ops.owner: duyiwei
  kubernetes.ops.region: hk
namespace: nestos
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/nestos-website-test
  newTag: a04808746276d8cb6f9c4bc911991c4f4d399f51
