apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-issuer
  name: opendesign-datapertus-openeuler-ingress
  namespace: opendesign-datapertus
spec:
  tls:
    - hosts:
        - datastat.openeuler.org
      secretName: datastat-openeuler-tls
  rules:
    - host: datastat.openeuler.org
      http:
        paths:
          - backend:
              serviceName: opendesign-datapertus-service
              servicePort: 80
            path: /

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-issuer
  name: opendesign-datapertus-opengauss-ingress
  namespace: opendesign-datapertus
spec:
  tls:
    - hosts:
        - datastat.opengauss.org
      secretName: datastat-opengauss-tls
  rules:
    - host: datastat.opengauss.org
      http:
        paths:
          - backend:
              serviceName: opendesign-datapertus-service
              servicePort: 80
            path: /

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-issuer
  name: opendesign-datapertus-mindspore-ingress
  namespace: opendesign-datapertus
spec:
  tls:
    - hosts:
        - datastat.mindspore.cn
      secretName: datastat-mindspore-tls
  rules:
    - host: datastat.mindspore.cn
      http:
        paths:
          - backend:
              serviceName: opendesign-datapertus-service
              servicePort: 80
            path: /

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-issuer
  name: opendesign-datapertus-openlookeng-ingress
  namespace: opendesign-datapertus
spec:
  tls:
    - hosts:
        - datastat.openlookeng.io
      secretName: datastat-openlookeng-tls
  rules:
    - host: datastat.openlookeng.io
      http:
        paths:
          - backend:
              serviceName: opendesign-datapertus-service
              servicePort: 80
            path: /