resources:
- namespace.yaml
- pvc.yaml
- sa.yaml
- workflow-manager
- workflow-runner
- event-selector
- workflow-event-handler
- post-extract-handler
- job-event-handler
- job-status-handler
- user-management
- exec-watcher
- exec-updator
- workflow-webhook
- workflow-schedule
- website
- etcd
- etcd-own
- kibana
- pods-monitor
namespace: openeuler-devops
commonAnnotations:
  kubernetes.ops.cluster: shanghai-test-cluster
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: openeuler
  kubernetes.ops.owner: zhangyizheng
  kubernetes.ops.region: sh
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization