apiVersion: kustomize.config.k8s.io/v1beta1
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe-async-server
  newTag: v1.0.20230510182055
kind: Kustomization
commonAnnotations:
  kubernetes.ops.cluster: infra-shanghai-test-cluster
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: alpine
  kubernetes.ops.owner: zhouzixian
  kubernetes.ops.region: hk
namespace: xihe-test-v2
resources:
- service.yaml
- deployment.yaml
- configmap.yaml
