resources:
- namespace.yaml
- ingress.yaml
- service.yaml
- deployment.yaml
- secret.yaml
- pvc.yaml
- autoscaler.yaml
- cronjob.yaml
commonAnnotations:
  kubernetes.ops.cluster: test
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: openeuler
  kubernetes.ops.owner: liuqi
  kubernetes.ops.region: hk
namespace: infra-cve-manager
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/app-icms
  newTag: "1695104049"
