resources:
- deployment.yaml
- service.yaml
commonAnnotations:
  kubernetes.ops.cluster: freesky-icsl-hk-cluster
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: ""
  kubernetes.ops.owner: liuwugang
  kubernetes.ops.region: hk
namespace: sca
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/icsl/sca-analysis
  newTag: f63343661ae92ef7c5e5eb233ba20a84fb4696ee
