resources:
- deployment.yaml
- namespace.yaml
- service.yaml
- ingress.yaml
- pvc.yaml
- job.yaml
namespace: mindspore-website
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/mindspore-website-test
  newTag: ed5793d2ead9c55936b9b3727890857973df366a
