resources:
- deployment.yaml
- namespace.yaml
- service.yaml
- ingress.yaml
- pvc.yaml
- job.yaml
namespace: mindspore-website
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/mindspore-website-test
  newTag: 3086aca562bc7883019f43a4088bccded197218a
