apiVersion: apps/v1
kind: Deployment
metadata:
  name: copr-backend
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      component: copr-backend
  template:
    metadata:
      labels:
        component: copr-backend
    spec:
      nodeSelector:
        copr: test
        os.architecture: amd64
      initContainers:
        - name: init-backend-resalloc
          image: ebiqe/alpine-nc:latest
          command: [ "sh", "-c", "until nc -z copr-resalloc.fedora-copr.svc.cluster.local 49100; do echo waiting for resalloc service ; sleep 2; done;" ]
      containers:
        - image: swr.cn-north-4.myhuaweicloud.com/opensourceway/copr/backend_httpd-test:v1.0.20230310165259
          imagePullPolicy: IfNotPresent
          name: httpd
          livenessProbe:
            tcpSocket:
              port: 5002
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 5002
            initialDelaySeconds: 5
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
          ports:
            - containerPort: 5002
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/copr/public_html/results
              name: copr-backend-data
            - mountPath: /var/lib/copr/public_html/stats
              name: copr-backend-stats-data
        - image: swr.cn-north-4.myhuaweicloud.com/opensourceway/copr/backend-test:v1.0.20230310164803
          imagePullPolicy: IfNotPresent
          name: log
          args: ["/usr/bin/copr_run_logger.py"]
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/copr-be.conf
              name: copr-secrets
              subPath: backend_copr-be.conf
            - mountPath: /var/lib/copr/public_html/results
              name: copr-backend-data
            - mountPath: /etc/copr/copr-be.conf
              name: copr-secrets
              subPath: backend_copr-be.conf
            - mountPath: /var/lib/copr/public_html/stats
              name: copr-backend-stats-data
        - image: swr.cn-north-4.myhuaweicloud.com/opensourceway/copr/backend-test:v1.0.20230310164803
          imagePullPolicy: IfNotPresent
          name: action
          args: ["/run-backend", "--sign-host", "copr-keygen", "/usr/bin/copr-run-dispatcher", "actions"]
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
          volumeMounts:
            - mountPath: /etc/copr/copr-be.conf
              name: copr-secrets
              subPath: backend_copr-be.conf
            - mountPath: /var/lib/copr/public_html/results
              name: copr-backend-data
            - mountPath: /var/lib/copr/public_html/stats
              name: copr-backend-stats-data
        - image: swr.cn-north-4.myhuaweicloud.com/opensourceway/copr/backend-test:v1.0.20230310164803
          imagePullPolicy: IfNotPresent
          name: build
          args: ["/run-backend", "--sign-host", "copr-keygen", "/usr/bin/copr-run-dispatcher", "builds"]
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
          volumeMounts:
            - mountPath: /home/copr/.ssh/builder_config
              name: copr-backend
              subPath: builder_config
            - mountPath: /home/copr/.ssh/id_rsa
              name: copr-secrets
              subPath: backend_id_rsa
            - mountPath: /home/copr/.ssh/id_rsa.pub
              name: copr-secrets
              subPath: backend_id_rsa.pub
            - mountPath: /var/lib/copr/public_html/results
              name: copr-backend-data
            - mountPath: /etc/copr/copr-be.conf
              name: copr-secrets
              subPath: backend_copr-be.conf
            - mountPath: /var/lib/copr/public_html/stats
              name: copr-backend-stats-data
      volumes:
        - name: copr-backend
          configMap:
            name: copr-backend
        - name: copr-backend-data
          persistentVolumeClaim:
            claimName: copr-backend-data
        - name: copr-backend-stats-data
          persistentVolumeClaim:
            claimName: copr-backend-stats-data
        - name: copr-secrets
          secret:
            secretName: copr-secrets